# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8081
    servlet:
        context-path: /admin
spring:
    http:
        multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true
    freemarker:
        suffix: .html #后缀名
        request-context-attribute: request
    #jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    datasource:
        url: jdbc:mysql://localhost:3306/cloudcomputingpower?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        #password: mysql123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 200
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select '1'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.ant.admin.dao

#log
#logging:
   # config:
        #classpath:logback.xml
    #path: /computingPower-log/my.log
    #path: logs/
    #file: admin.log
